{"name": "计算除法中正数、负数相除情况、被除数为0", "status": "passed", "attachments": [{"name": "log", "source": "41e0ba0c-7078-47e8-b5ca-e3ae8e25b63b-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "2"}, {"name": "b", "value": "2"}, {"name": "expect", "value": "1"}], "start": 1626702690125, "stop": 1626702690125, "uuid": "e8a5001e-5e3c-4a82-a9c2-ee3543f9f3c9", "historyId": "beacca5577865033e0236a677521661f", "testCaseId": "540ae9490c5546cd9bf0d8f636e8d760", "fullName": "test_calcul_yml.Test_calculate#test_division", "labels": [{"name": "feature", "value": "计算器模块"}, {"name": "story", "value": "除法计算成功"}, {"name": "suite", "value": "test_calcul_yml"}, {"name": "subSuite", "value": "Test_calculate"}, {"name": "host", "value": "PC-20200730PITZ"}, {"name": "thread", "value": "12300-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calcul_yml"}]}