{"name": "计算除法中正数、负数相除情况、被除数为0", "status": "passed", "attachments": [{"name": "log", "source": "75782c4a-10ec-40bc-8a55-dad56ab56846-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "-10"}, {"name": "b", "value": "-5"}, {"name": "expect", "value": "2"}], "start": 1626702690131, "stop": 1626702690131, "uuid": "7e44b2de-95d9-47d3-940c-cc27a492f6e2", "historyId": "1c6532a788c5e1774b5b32552a178924", "testCaseId": "540ae9490c5546cd9bf0d8f636e8d760", "fullName": "test_calcul_yml.Test_calculate#test_division", "labels": [{"name": "feature", "value": "计算器模块"}, {"name": "story", "value": "除法计算成功"}, {"name": "suite", "value": "test_calcul_yml"}, {"name": "subSuite", "value": "Test_calculate"}, {"name": "host", "value": "PC-20200730PITZ"}, {"name": "thread", "value": "12300-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calcul_yml"}]}