{"name": "计算除法中正数、负数相除情况、被除数为0", "status": "passed", "attachments": [{"name": "log", "source": "b39afff5-1f1f-4082-ae54-2ccf5a91f8e0-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "a", "value": "-10"}, {"name": "b", "value": "5"}, {"name": "expect", "value": "-2"}], "start": 1626702690137, "stop": 1626702690137, "uuid": "d714f0dc-3e4d-4fee-af0d-1d0dfe52412e", "historyId": "7d44e8511fefeb277d2a55f989edfd7f", "testCaseId": "540ae9490c5546cd9bf0d8f636e8d760", "fullName": "test_calcul_yml.Test_calculate#test_division", "labels": [{"name": "feature", "value": "计算器模块"}, {"name": "story", "value": "除法计算成功"}, {"name": "suite", "value": "test_calcul_yml"}, {"name": "subSuite", "value": "Test_calculate"}, {"name": "host", "value": "PC-20200730PITZ"}, {"name": "thread", "value": "12300-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calcul_yml"}]}